services:
    app:
        build:
            context: .
            target: development
        volumes:
            - ./src:/usr/src/app/src
        command: npm run dev
    db:
        ports:
            - "4361:5432"
